# Generated by Django 3.1.4 on 2021-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('player_count', models.IntegerField(default=0)),
                ('player_percent', models.FloatField(default=0)),
                ('player_position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('players_list', models.TextField(max_length=200)),
                ('team_power', models.IntegerField(default=0)),
            ],
        ),
    ]
